### ISSUE TITLE
[BUG] Data race due to mutable feature vectors being shared across thread boundaries when using concurrent segment search

### ISSUE THREAD

**Issue by jhinch-at-atlassian-com** [opensearch-project/opensearch-learning-to-rank-base#52]
### What is the bug?

OpenSearch 2.12 stablised [concurrent segment search](https://opensearch.org/docs/2.12/search-plugins/concurrent-segment-search/) which results in segments being search on different threads in parallel. The LTR plugin makes use of a [MutableSupplier](https://github.com/opensearch-project/opensearch-learning-to-rank-base/blob/main/src/main/java/com/o19s/es/ltr/utils/Suppliers.java#L67) to share feature vectors between different parts of the code. For example in [DerivedExpressionQuery](https://github.com/opensearch-project/opensearch-learning-to-rank-base/blob/main/src/main/java/com/o19s/es/ltr/query/DerivedExpressionQuery.java#L257) and [ScriptFeature](https://github.com/opensearch-project/opensearch-learning-to-rank-base/blob/main/src/main/java/com/o19s/es/ltr/feature/store/ScriptFeature.java#L293). Due to the implementation being made using an atomic reference (https://github.com/opensearch-project/opensearch-learning-to-rank-base/commit/e34d607c73f3f5f539f92c437cd0b2e147be0419) this results in feature vectors potentially for different documents to be retrieved, resulting in the wrong feature scores and also data races.

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?

The underlying issue seems to be that the vector is being shared across `LeafReaderContext` boundaries. If either a supplier was created one per `LeafReaderContext` or the feature vector sharing is kept unique for each `LeafReaderContext` then it should work as expected

**Comment by andrross** [comment]
Thanks @jhinch-at-atlassian-com.

@msfroh can you share any thoughts here?

**Comment by msfroh** [comment]
Yeah... this comment looks like a bit of a smoking gun: https://github.com/opensearch-project/opensearch-learning-to-rank-base/blob/d3e1dd1e469f44bb50fec3c28919436a7704ea66/src/main/java/com/o19s/es/ltr/query/RankerQuery.java#L203-L206

Now that we are using the concurrent `CollectorManager` API, the predicted breakage came true.

**Comment by msfroh** [comment]
@jhinch-at-atlassian-com -- Would you be able to develop and test a fix for this? 

I think you're right that scoping the supplier to the given `LeafCollector` would work. Now that Lucene `Weight`s can create a `ScorerSupplier` per `LeafReaderContext`, we should modify any custom weights to implement the `scorerSupplier` method (since I think the old `scorer` method was removed in Lucene 10? Or at least `scorerSupplier` is the preferred method now.) Any shared state should probably be scoped to the returned `ScorerSupplier`. That will also work if/when we upgrade to Lucene 10, which now support intra-segment concurrency -- so multiple `ScorerSupplier`s (and `LeafCollector`s) may be created for the same `LeafReaderContext`.

**Comment by jhinch-at-atlassian-com** [comment]
I had a brief exploration into fixing this. It looks like using a thread local is the most convenient fix. The thread local is created when the a new feature vector is created and cleared after the ranker score is computed. I will raise a PR with the candidate fix shortly
